image: alpine:latest

before_script:
  - docker info


# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
#pages:
test:
  script:
  - echo "hi!"
  - mkdir .public
  - cp -r * .public
  - mv .public public
  - echo "Done!"
  artifacts:
    paths:
    - public
  only:
  - master
